Update release build with compliance tasks
PowerShell/PSReadLine pull request #1260
Opened 2019-12-20 22:00 UTC by daxian-dbw

Update release build with compliance tasks

2019-12-20 23:02 UTC, adityapatwardhan requested changes

2019-12-20 23:02 UTC, adityapatwardhan commented on .vsts-ci/templates/compliance.yml
> +    codeBaseName: $(CodeBaseName)
Also update the value of CodeBaseName variable

2019-12-20 23:29 UTC, adityapatwardhan approved these changes

2019-12-20 23:58 UTC, daxian-dbw commented
Validating the changes in a AzureDevOps build, will wait till it succeeds.

2019-12-21 17:14 UTC, lzybkr commented on .vsts-ci/templates/compliance.yml
> +    AnalyzeTarget: '$(Build.SourcesDirectory)\PSThreadJob\bin\${{ parameters.configuration }}\${{ parameters.framework }}\*.dll'
PSThreadJob?

2019-12-21 18:16 UTC, daxian-dbw commented on .vsts-ci/templates/compliance.yml
> +    AnalyzeTarget: '$(Build.SourcesDirectory)\PSThreadJob\bin\${{ parameters.configuration }}\${{ parameters.framework }}\*.dll'
oops, copy-paste mistake ... will update soon.

2019-12-21 18:56 UTC, daxian-dbw commented
@adityapatwardhan the Azure DevOps build failed because the defender scan took more than an hour and the build agent cancelled the task.

2020-01-03 00:26 UTC, daxian-dbw commented
Increase the timeout to 200 minutes. Test build has been kicked off in Azure DevOps.

2020-01-03 18:06 UTC, daxian-dbw commented
@adityapatwardhan The test build in Azure DevOps has passed. It took 1.5 hours, and the API scan itself took 1 hour 17 minutes :)

2020-01-03 18:07 UTC, merged