Add argument selection handler to sample profile
PowerShell/PSReadLine pull request #1947
Opened 2020-11-12 08:57 UTC by ThePSAdmin

# PR Summary
This adds a handler to the sample PSReadLine profile which cycles through the arguments on the current command line, and selects the entire argument. This makes it simpler to quickly change an argument when recalling a command from the history, or changing the values of an argument when using a suggested command from a PSReadLine predictor plugin. 

## PR Checklist

- [X] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [X] Summarized changes
- [ ] Make sure you've added one or more new tests
- [X] Make sure you've tested these changes in terminals that PowerShell is commonly used in (i.e. conhost.exe, Windows Terminal, Visual Studio Code Integrated Terminal, etc.)
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] Documentation needed at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)
        - [ ] Doc Issue filed:

2020-11-12 18:56 UTC, lzybkr requested changes
Looks pretty good. Formatting should be consistent with the rest of the file, e.g. use 4 spaces for indent.

2020-11-12 18:56 UTC, lzybkr commented on PSReadLine/SamplePSReadLineProfile.ps1
> +      $nextAst = $asts[$arg - 1]
This could cause an exception if strict mode was turned on.

2020-11-12 18:56 UTC, lzybkr commented on PSReadLine/SamplePSReadLineProfile.ps1
> +      if ($null -eq $nextAst) {
`$nextAst` should probably be initialized to `$null` before the loop to ensure no strict mode errors on an undefined variable.

2020-11-12 18:56 UTC, lzybkr commented on PSReadLine/SamplePSReadLineProfile.ps1
> +    if ($nextAst.StringConstantType -ne [System.Management.Automation.Language.StringConstantType]::BareWord) {
Possible NullReferenceException on `$nextAst`.

2020-11-12 18:56 UTC, lzybkr commented on PSReadLine/SamplePSReadLineProfile.ps1
> +        $args[0] -is [System.Management.Automation.Language.StringConstantExpressionAst] -and
Why just strings? Why not expressions too?

2020-11-12 19:12 UTC, daxian-dbw reviewed
Very interesting! The Az predictor team is actually looking for a similar experience, and we may have a built-in function in future.

2020-11-12 19:12 UTC, daxian-dbw commented on PSReadLine/SamplePSReadLineProfile.ps1
> +        $args[0] -is [System.Management.Automation.Language.StringConstantExpressionAst] -and
Can you take into account `ConstantExpressionAst` as well? It currently skip a constant value like `100` when looping through the arguments.

2020-11-12 19:12 UTC, daxian-dbw commented on PSReadLine/SamplePSReadLineProfile.ps1
> +  }
Please add a new line in the end.

2020-11-13 17:55 UTC, daxian-dbw reviewed
Looks good. I left 2 minor comments, once you address them we can merge the PR.

2020-11-13 17:55 UTC, daxian-dbw commented on PSReadLine/SamplePSReadLineProfile.ps1
> +    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$ast, [ref]$tokens, [ref]$parseErrors, [ref]$cursor)
```suggestion
    $ast = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$ast, [ref]$$null, [ref]$null, [ref]$cursor)
```

2020-11-13 17:55 UTC, daxian-dbw commented on PSReadLine/SamplePSReadLineProfile.ps1
> +  }
```suggestion
}
```

2020-11-17 04:34 UTC, daxian-dbw approved these changes

2020-11-17 04:37 UTC, daxian-dbw commented
@lzybkr Could you take another look?

2020-11-18 00:39 UTC, lzybkr requested changes
If there are no arguments, the cursor shouldn't move. An early return (and a Ding?) also avoids other potential issues, like indexing out of bounds (which is reported in V2 strict mode.)

I have conflicting feelings about not selecting arguments, but this is a sample, so I don't care if that behavior is changed. I say conflicting because I tried this one a command line like:

```
echoargs -a 1 --long 2
```

Repeatedly pressing <kbd>Alt+a</kbd> would select `1`, `--long`, and `2`. In this example, it's surprising that `-a` is not selected but `--long` is. I know why, but it does feel weird.

2020-11-18 00:39 UTC, lzybkr commented on PSReadLine/SamplePSReadLineProfile.ps1
> +
```suggestion

    if ($asts.Count -eq 0) {
        [Microsoft.PowerShell.PSConsoleReadLine]::Ding()
        return
    }
```

2020-11-18 22:17 UTC, lzybkr approved these changes

2020-11-18 22:17 UTC, merged