[Vi-Mode] Supports di' and di" commands (quoted text objects)
PowerShell/PSReadLine pull request #3791
Opened 2023-08-23 23:32 UTC by springcomp

# PR Summary

Fixes #3790.

## PR Checklist

- [x] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [x] Summarized changes
- [x] Make sure you've added one or more new tests
- [x] Make sure you've tested these changes in terminals that PowerShell is commonly used in (i.e. conhost.exe, Windows Terminal, Visual Studio Code Integrated Terminal, etc.)
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] Documentation needed at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)
        - [ ] Doc Issue filed: 

As #2059 has been readily accepted, we have not had the time to discuss the documentation.
This PR, like #2059, wire keybindings to private methods. Please, let me know how to best document this behaviour.

2023-10-23 20:35 UTC, daxian-dbw commented
Before moving forward with more 3-key chord supports, we need to first figure out how to make `Get/Set-PSReadLineKeyHandler` support chords with more than 2 keys. Today, `_chordDispatchTable` is a 2-level dictionary, and hence it only really supports 2-key chords. `Get/Set-PSReadLineKeyHandler` are implemented under that assumption.

By looking at #2059 again, I think I merged it a little too prematurely :)
Today, we have two 3-key chords built-in:
- `<d,g,g>` -- implemented by having `g` mapped to `ViDBChord` in the `DTable` with a `DGTable` that maps the second `g` to the handler.
- `<d,w,i>` --implemented by #2059.

There are 2 concerns here:
1. Their implementation should be consistent in the way how the 3rd level dictionary is stored.
2. Changes to VI key binding data structure are needed to make `Get/Set-PSReadLineKeyHandler` to support chords with 3 keys (are we stopping at 3-key chords for VI mode here? maybe we should and not support chords with more than 3 keys).

I think we should first resolve the above concerns before adding more text object commands.

2023-10-23 20:36 UTC, daxian-dbw requested changes
Before moving forward with more 3-key chord supports, we need to first figure out how to make `Get/Set-PSReadLineKeyHandler` support chords with more than 2 keys. Today, `_chordDispatchTable` is a 2-level dictionary, and hence it only really supports 2-key chords. `Get/Set-PSReadLineKeyHandler` are implemented under that assumption.

By looking at #2059 again, I think I merged it a little too prematurely :)
Today, we have two 3-key chords built-in:
- `<d,g,g>` -- implemented by having `g` mapped to `ViDBChord` in the `DTable` with a `DGTable` that maps the second `g` to the handler.
- `<d,w,i>` --implemented by #2059.

There are 2 concerns here:
1. Their implementation should be consistent in the way how the 3rd level dictionary is stored.
2. Changes to VI key binding data structure are needed to make `Get/Set-PSReadLineKeyHandler` to support chords with 3 keys (are we stopping at 3-key chords for VI mode here? maybe we should and not support chords with more than 3 keys).

I think we should first resolve the above concerns before adding more text object commands.

2023-10-23 20:36 UTC, daxian-dbw commented on PSReadLine/StringBuilderTextObjectExtensions.cs
> +        internal static int GetBeginningOfLogicalLinePos(this StringBuilder buffer, int current)
It seems `GetBeginningOfLogicalLinePos` and `GetEndOfLogicalLinePos` shoudl be put in `StringBuilderLinewiseExtensions` instead.

2023-10-23 20:36 UTC, daxian-dbw commented on PSReadLine/StringBuilderTextObjectExtensions.cs
> +using System.Management.Automation;
Added by mistake? It doesn't seem to be needed by the code changes in this file.

2023-10-23 21:00 UTC, daxian-dbw commented
BTW, the `<d,i>` shows up in the results of `Get-PSReadLineKeyHandler`:
```
User defined functions
======================

Key   Function          Description
---   --------          -----------
<d,i> ChordViTextObject ChordViTextObject
```

Two problems here:
1. `ChordViTextObject` is not put in `GetDisplayGrouping(string function)`, so it's displayed as **User defined functions**.
2. The chord `<d,i>` is incomplete -- users will try using it but observe no result (or unexpected result).

2023-10-31 16:36 UTC, closed without merging

2023-10-31 16:45 UTC, springcomp commented
@daxian-dbw  I have published #3853 to address your feedback, re-working #2059 in the process.
I’m happy for this current PR to be closed as I will be able to move the code forward in a better shape if #3853 is accepted.