Enable building with dotnetcli for non-Windows
PowerShell/PSReadLine pull request #692
Opened 2018-05-30 04:24 UTC by SteveL-MSFT

Ported csproj to use dotnetcli.  When run from PSCore6, builds for netcoreapp21.  When run from Windows PowerShell 5.1, builds for net461.  Tests ran on Windows PowerShell, PSCore6 Windows, PSCore6 Ubuntu 18.04, and PSCore6 macOS all passing.  Linux run requires xclip to be installed as that is necessary for clipboard to function (which tests depend upon).  Using dotnetsdk 2.1.  Appropriate .Net Framework 4.6.1 SDK is required for Windows PowerShell build.

Fix #652

2018-05-30 13:31 UTC, lzybkr commented
You should add a new task in `PSReadLine.build.ps1` instead of adding the new file `build.ps1`.

The new task should probably be invoked from `appveyor.yml`.

And I would much rather see changes to `PSReadLine\PSReadLine.csproj` - I'm guessing there are about 2 lines of real difference between the files.

2018-05-30 16:06 UTC, SteveL-MSFT commented
@lzybkr I'm fine having a single csproj, but wasn't sure if you preferred keeping the existing project as-is.

2018-05-30 16:18 UTC, lzybkr commented
Does building against PowerShell Standard work against Windows PowerShell 5.1 on Win7 and Win10 without shipping type forwarding dlls? If so, they fine, but I'm guessing there isn't a clean solution to that problem yet.

A single csproj can build multiple ways with conditions though - and that's what I was suggesting.

2018-05-30 18:00 UTC, SteveL-MSFT commented
@lzybkr If Win7 doesn't have .Net 4.7, the shims are needed.  Newer Win10 has 4.7.x.  We plan to have a module that contains the .Net Std shims that other modules can reference.

2018-06-01 14:35 UTC, SteveL-MSFT commented
@lzybkr are you ok if we move both the Windows and non-Windows build to dotnetcli?  Would simplify things quite a bit.

2018-06-01 16:50 UTC, lzybkr commented
@SteveL-MSFT - if you submit a PR so I can see how it's simpler, that would help.

I don't want to distribute unnecessary private copies of dlls, I'm already unhappy about needing `System.Runtime.InteropServices.RuntimeInformation.dll`.

I also don't want runtime logic that might affect startup time, e.g. path searching for type forwarders dlls.

2018-06-02 05:06 UTC, SteveL-MSFT commented
I'm going to have to put this on hold for now.  Got it building and tests running with dotnetcli, but tests fail to run correctly.

2018-07-17 03:13 UTC, SteveL-MSFT commented
Almost got this working

2018-07-21 06:18 UTC, SteveL-MSFT commented
@lzybkr I think this is ready for review

2018-08-19 20:49 UTC, lzybkr requested changes
I think you should add instructions for building to `README.md` so I can easily point people to what they need to install.

You also need to try running the tests from VS. You did not update the `TestPSReadLine` project and that fails to build, preventing tests from running. (That project is used for interactive development/testing without affecting PowerShell by installing the module.)

2018-08-19 20:49 UTC, lzybkr commented on PSReadLine.build.ps1
> +task RunTests {
You removed `BuildTests` - please put in the dependency so one can run `Invoke-Build Clean,RunTests` .

2018-08-19 20:49 UTC, lzybkr commented on PSReadLine.build.ps1
> -    Copy-Item PSReadLine/bin/$Configuration/System.Runtime.InteropServices.RuntimeInformation.dll $targetDir
Why did you remove copying `System.Runtime.InteropServices.RuntimeInformation.dll`? Is this dll installed everywhere PSReadLine including Win7?

2018-08-20 15:18 UTC, SteveL-MSFT commented on PSReadLine.build.ps1
> +        $psAssemblies = "System.Management.Automation.dll", "Newtonsoft.Json.dll", "System.Management.dll", "System.DirectoryServices.dll"
The new SDK we published should remove the need for this line, it was broken previously

2018-09-26 20:26 UTC, SteveL-MSFT commented on PSReadLine/Clipboard.cs
> +                if (process.ExitCode != 0)
will fix

2018-09-26 20:37 UTC, SteveL-MSFT commented
@lzybkr verified solution builds and tests run in VS2017

2018-09-26 20:38 UTC, lzybkr commented on PSReadLine.build.ps1
> +        $psAssemblies = "System.Management.Automation.dll", "Newtonsoft.Json.dll", "System.Management.dll", "System.DirectoryServices.dll"
OK - we'll put off using `-runtime` until PowerShellGet supports installing just the necessary binaries for a given install.

2018-09-28 16:18 UTC, lzybkr submitted a review, later dismissed

2018-09-28 18:05 UTC, SteveL-MSFT commented
@lzybkr the .psd1 file wasn't changed in this PR and looking in my repo, it's still set to 2.0.0

2018-09-30 05:15 UTC, lzybkr approved these changes

2018-09-30 05:17 UTC, merged